import { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "modern-2026",
    name: "The New World Order",
    description: "Global power is fragmenting. The US-China rivalry intensifies as the EU seeks strategic autonomy, Russia rebuilds, and regional powers rise. AI and climate change reshape every calculation.",
    year: 2026,
    scenario: "It is 2026. The global order is fracturing along new fault lines. The US and China are locked in technological and economic competition. Russia's war in Ukraine has reshaped European security. AI is transforming economies and warfare. Climate disasters strain global cooperation. Regional powers like India, Turkey, Saudi Arabia, and Brazil are asserting independence from traditional blocs. The old rules-based international order is giving way to something new and uncertain.",
    difficulty: "Realistic",
    suggestedNations: ["USA", "China", "Russia", "India", "United Kingdom", "France", "Germany", "Brazil", "Turkey", "Japan"],
    category: "modern",
    icon: "globe",
  },
  {
    id: "ww2-1939",
    name: "World War II",
    description: "September 1939. Germany has invaded Poland. Britain and France declare war. The world holds its breath as the deadliest conflict in human history begins.",
    year: 1939,
    scenario: "September 1, 1939. Nazi Germany has invaded Poland with overwhelming force, unleashing Blitzkrieg warfare. Britain and France have declared war on Germany. The Soviet Union, bound by the Molotov-Ribbentrop Pact, has invaded Poland from the east. Italy under Mussolini wavers. Japan is already at war in China. The United States remains isolationist but watches with growing alarm. The League of Nations has failed. Total war looms over every continent.",
    difficulty: "Hardcore",
    suggestedNations: ["Germany", "United Kingdom", "France", "USA", "Russia", "Japan", "Italy", "China", "Poland", "Canada"],
    category: "historical",
    icon: "war",
  },
  {
    id: "cold-war-1962",
    name: "The Cuban Missile Crisis",
    description: "October 1962. Soviet nuclear missiles discovered in Cuba. The world stands on the brink of nuclear annihilation. Every decision could be humanity's last.",
    year: 1962,
    scenario: "October 16, 1962. U-2 reconnaissance has confirmed Soviet nuclear missiles in Cuba, just 90 miles from Florida. President Kennedy convenes ExComm. The Joint Chiefs want an invasion. Khrushchev insists the missiles are defensive. Castro prepares for invasion. NATO allies are nervous. The world is 13 days from potential nuclear holocaust. Every diplomatic signal, military movement, and backroom deal could determine the fate of civilization.",
    difficulty: "Hardcore",
    suggestedNations: ["USA", "Russia", "Cuba", "United Kingdom", "France", "China", "Germany", "Turkey", "Brazil", "India"],
    category: "historical",
    icon: "nuke",
  },
  {
    id: "rome-fall-476",
    name: "The Fall of Rome",
    description: "The Western Roman Empire crumbles. Barbarian kingdoms rise from its ashes. Can you preserve civilization or forge a new world from the ruins?",
    year: 476,
    scenario: "The year is 476 AD. Romulus Augustulus, the last Western Roman Emperor, has been deposed by Odoacer. The Western Empire is no more, but the Eastern Roman Empire in Constantinople endures under Emperor Zeno. Barbarian kingdoms carve up the former Roman territories: the Visigoths hold Hispania, the Franks expand in Gaul, the Vandals control North Africa. The Ostrogoths eye Italy. The Sassanid Empire threatens the East. The Pope in Rome gains spiritual authority as temporal power collapses. Trade routes falter, cities shrink, but new civilizations are being born.",
    difficulty: "Realistic",
    suggestedNations: ["Italy", "Turkey", "France", "Spain", "United Kingdom", "Germany", "Egypt", "Iran", "Tunisia", "Greece"],
    category: "historical",
    icon: "crown",
  },
  {
    id: "exploration-1492",
    name: "Age of Exploration",
    description: "Columbus has reached the New World. European powers race to claim continents, forge trade empires, and reshape the globe forever.",
    year: 1492,
    scenario: "October 1492. Christopher Columbus has made landfall in the Caribbean, believing he has reached Asia. Spain and Portugal are the dominant naval powers, their rivalry arbitrated by the Pope. England, France, and the Netherlands watch enviously. The Ottoman Empire controls Eastern Mediterranean trade routes, making the search for western passages to Asia urgent. The Aztec and Inca empires flourish in the Americas, unaware of the approaching storm. China under the Ming Dynasty has turned inward after Zheng He's great voyages. The world is about to be connected for the first time.",
    difficulty: "Realistic",
    suggestedNations: ["Spain", "Portugal", "United Kingdom", "France", "Netherlands", "Turkey", "Italy", "China", "Mexico", "Peru"],
    category: "historical",
    icon: "ship",
  },
  {
    id: "ww1-1914",
    name: "The Great War",
    description: "Archduke Franz Ferdinand is dead. The alliance system drags Europe into a war that will shatter empires and birth the modern world.",
    year: 1914,
    scenario: "June 28, 1914. Archduke Franz Ferdinand of Austria-Hungary has been assassinated in Sarajevo. The alliance system activates like a chain reaction: Austria-Hungary issues an ultimatum to Serbia. Russia mobilizes to defend Serbia. Germany backs Austria and activates the Schlieffen Plan. France is pulled in by alliance. Belgium's neutrality is violated. Britain enters to honor the Treaty of London. The Ottoman Empire wavers between neutrality and joining the Central Powers. Italy debates which side serves its interests. Japan eyes German colonies in the Pacific. The war everyone expected to be 'over by Christmas' is about to consume a generation.",
    difficulty: "Hardcore",
    suggestedNations: ["United Kingdom", "France", "Germany", "Russia", "Austria", "Turkey", "Italy", "USA", "Japan", "Serbia"],
    category: "historical",
    icon: "war",
  },
  {
    id: "napoleon-1799",
    name: "Rise of Napoleon",
    description: "A young Corsican general seizes power in revolutionary France. Europe's monarchies unite against him. An age of empires and revolution begins.",
    year: 1799,
    scenario: "November 1799. Napoleon Bonaparte has overthrown the Directory in a coup d'etat and declared himself First Consul of France. The French Revolution has terrified every monarchy in Europe. Coalition wars rage. Britain rules the seas but struggles on land. Austria and Prussia contest Central Europe. Russia under Tsar Paul I is unpredictable. The Ottoman Empire declines. Spain is weakened. The Haitian Revolution shakes colonial powers. Revolutionary ideals of liberty, equality, and fraternity clash with the old order of kings and empires. Napoleon dreams of remaking Europe.",
    difficulty: "Realistic",
    suggestedNations: ["France", "United Kingdom", "Austria", "Russia", "Spain", "Germany", "Italy", "Netherlands", "Turkey", "Egypt"],
    category: "historical",
    icon: "crown",
  },
  {
    id: "zombie-2026",
    name: "The Dead Rising",
    description: "A mysterious pathogen turns the dead into predators. Governments collapse. Civilization fractures. Only the cunning survive.",
    year: 2026,
    scenario: "Patient Zero was identified in a remote research facility. Within weeks, a mysterious pathogen spread globally through air travel. The infected become aggressive and mindless within hours. Major cities fell first - dense populations became death traps. Governments enacted martial law, then collapsed. Military units fragment between those defending civilians and those seizing power. Nuclear powers face the terrible question of whether to sterilize infected zones. Small fortified communities become the last bastions of civilization. International cooperation is virtually impossible. Resources dwindle. Winter offers temporary respite in northern regions. The dead do not negotiate.",
    difficulty: "Hardcore",
    suggestedNations: ["USA", "Russia", "United Kingdom", "Japan", "Australia", "Switzerland", "New Zealand", "Canada", "South Korea", "Norway"],
    category: "fictional",
    icon: "skull",
  },
  {
    id: "alt-soviet-1995",
    name: "The USSR Endures",
    description: "What if the Soviet Union never fell? Gorbachev's reforms succeeded. Two superpowers face off in a transformed Cold War with new technologies.",
    year: 1995,
    scenario: "It is 1995, but history diverged in 1991. Gorbachev's reforms succeeded - the Soviet Union restructured but survived as a democratic socialist federation. The Cold War continues but has thawed considerably. Both superpowers race to harness the new internet technology. China, emboldened by its own reforms, becomes a third pole of power. The European Union struggles to define itself between two giants. The Middle East remains volatile after the Gulf War. Africa sees a wave of democratic transitions. Space cooperation programs hint at a new era, but old suspicions run deep. Nuclear arsenals remain on hair-trigger alert.",
    difficulty: "Realistic",
    suggestedNations: ["USA", "Russia", "China", "Germany", "Japan", "United Kingdom", "France", "India", "Brazil", "South Africa"],
    category: "alternate",
    icon: "flag",
  },
  {
    id: "climate-2040",
    name: "The Great Collapse",
    description: "2040. Climate tipping points cascade. Mass migration reshapes borders. Resource wars erupt. Can you lead your nation through the crisis of the century?",
    year: 2040,
    scenario: "The year is 2040. The worst climate predictions have come true. The Arctic is ice-free in summer. Sea levels have risen 0.5 meters, flooding major coastal cities. The Amazon rainforest has crossed a tipping point and is becoming savanna. Extreme weather has devastated global agriculture. Over 200 million climate refugees are on the move. Water wars rage in Central Asia and the Middle East. The Sahel has become uninhabitable. Wealthy nations build walls while poor nations collapse. A few countries have adapted through massive investment in green technology and nuclear power. International institutions have fractured under the strain. Military conflicts over water, arable land, and habitable territory are escalating. This is the century's defining crisis.",
    difficulty: "Hardcore",
    suggestedNations: ["India", "USA", "China", "Brazil", "Germany", "Nigeria", "Russia", "Australia", "Indonesia", "Egypt"],
    category: "alternate",
    icon: "fire",
  },
  {
    id: "three-kingdoms-220",
    name: "Three Kingdoms",
    description: "The Han Dynasty collapses. Warlords carve China into three rival kingdoms. Strategy, betrayal, and legendary heroes define an age.",
    year: 220,
    scenario: "The year is 220 AD. The Han Dynasty has formally ended. China splinters into three kingdoms: Wei in the north under the cunning Cao Cao's descendants, Shu in the southwest led by the idealistic Liu Bei's legacy and the genius strategist Zhuge Liang, and Wu in the southeast under the Sun family. The Roman Empire is at its height in the West. The Parthian Empire controls Persia. Trade flows along the Silk Road connecting East and West. Nomadic tribes pressure China's northern borders. Each kingdom claims the Mandate of Heaven and the right to reunify China. Brilliant strategists, legendary warriors, and ruthless politicians clash in one of history's greatest three-way struggles.",
    difficulty: "Realistic",
    suggestedNations: ["China", "Mongolia", "Vietnam", "South Korea", "Japan", "India", "Iran", "Turkey", "Italy", "Egypt"],
    category: "historical",
    icon: "sword",
  },
  {
    id: "space-race-2035",
    name: "The New Space Race",
    description: "Mars colonization has begun. Nations and corporations compete for the solar system's resources. Earth's conflicts extend into orbit.",
    year: 2035,
    scenario: "The year is 2035. SpaceX established the first permanent Mars colony in 2032, but China's CNSA landed its own mission months later. A new space race between the US, China, ESA, India, and private corporations is in full swing. Lunar mining operations provide Helium-3 for experimental fusion reactors. Space-based solar power stations orbit Earth. Military satellites and anti-satellite weapons create tension. The Outer Space Treaty of 1967 is considered obsolete. Asteroid mining promises unlimited resources but raises questions about who owns space. A new frontier of human civilization is opening - and with it, new conflicts over who controls humanity's future among the stars.",
    difficulty: "Realistic",
    suggestedNations: ["USA", "China", "India", "Russia", "Japan", "France", "Germany", "South Korea", "United Kingdom", "Brazil"],
    category: "alternate",
    icon: "rocket",
  },
];

export const PRESET_CATEGORIES = [
  { id: "historical", name: "Historical", description: "Relive pivotal moments in history" },
  { id: "modern", name: "Modern", description: "Navigate today's geopolitical landscape" },
  { id: "alternate", name: "Alternate History", description: "What if things went differently?" },
  { id: "fictional", name: "Fictional", description: "Impossible scenarios, unlimited creativity" },
] as const;

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find(p => p.id === id);
}

export function getPresetsByCategory(category: string): Preset[] {
  return PRESETS.filter(p => p.category === category);
}
